"""First-wave Art History → DNA → UI Translation rebuild (offline-safe)."""
from pathlib import Path
import json
from datetime import datetime, timezone, timedelta

ROOT=Path('design_style_library'); OUT=ROOT/'styles'; NOW=datetime.now(timezone(timedelta(hours=8))).isoformat(timespec='seconds')
S={
'art_nouveau':{'en':'Art Nouveau','zh':'新艺术','period':'c. 1890–1910','core':['organic continuous curve','botanical structural motif','integrated decorative frame','asymmetrical composition'], 'secondary':['restrained natural palette','flat printed illustration'], 'avoid':'“绿色 + 花朵 + 普通仪表盘”不是 Art Nouveau；曲线、边框和非对称结构必须参与信息组织。','refs':[('The Met — Art Nouveau overview','https://www.metmuseum.org/toah/hd/artn/hd_artn.htm'),('The Met — Mucha decorative panel study','https://www.metmuseum.org/art/collection/search/283253'),('The Met — Loie Fuller Dancing','https://www.metmuseum.org/art/collection/search/287807')]},
'art_deco':{'en':'Art Deco','zh':'装饰艺术','period':'c. 1910–1939','core':['axial symmetry','stepped geometric massing','sunburst and fan rhythm','luxury linear framing'], 'secondary':['black/gold/cream contrast','vertical emphasis'], 'avoid':'金色描边加在普通卡片上不是 Art Deco；必须建立对称、阶梯比例与放射节奏。','refs':[('The Met — Decorative Arts of the Twentieth Century','https://resources.metmuseum.org/resources/metpublications/pdf/Decorative_Arts_of_the_Twentieth_Century_The_Metropolitan_Museum_of_Art_Bulletin_v_37_no_3_Winter_1979_1980.pdf'),('The Met — Heilbrunn Art Deco essay','https://www.metmuseum.org/toah/hd/artd/hd_artd.htm'),('Victoria and Albert Museum — Art Deco','https://www.vam.ac.uk/articles/art-deco-an-introduction')]},
'bauhaus':{'en':'Bauhaus','zh':'包豪斯','period':'1919–1933','core':['functional geometry','asymmetric grid','shape-based information hierarchy','limited primary color as function'], 'secondary':['sans-serif hierarchy','industrial surface'], 'avoid':'随机红黄蓝圆形不是 Bauhaus；色彩、比例和几何必须承担功能分区。','refs':[('MoMA — Moholy-Nagy, Konstruktionen','https://www.moma.org/collection/works/68722'),('Bauhaus Dessau Foundation — Bauhaus history','https://www.bauhaus-dessau.de/en/geschichte.html'),('The Met — Bauhaus essay','https://www.metmuseum.org/toah/hd/bauh/hd_bauh.htm')]},
'constructivism':{'en':'Constructivism','zh':'构成主义','period':'c. 1915–1930','core':['diagonal tension','asymmetric scale contrast','intersecting planes and text','directional visual force'], 'secondary':['limited red/black/cream','photomontage crop'], 'avoid':'红黑配色的常规网格不是构成主义；阅读方向、模块尺寸和层叠必须被对角张力重构。','refs':[('MoMA — Constructivism term','https://www.moma.org/collection/terms/constructivism'),('MoMA — Aleksei Gan, Konstruktivizm','https://www.moma.org/collection/works/12867'),('MoMA — Die Konstruktivisten poster','https://www.moma.org/collection/works/6746')]},
'de_stijl':{'en':'De Stijl','zh':'风格派','period':'1917–1931','core':['orthogonal grid','asymmetry through proportion','rectilinear planes','primary-color structural accents'], 'secondary':['black structural lines','white spatial field'], 'avoid':'仅把界面涂成红黄蓝不是风格派；需要让线、比例、空白与矩形平面形成秩序。','refs':[('MoMA — De Stijl term','https://www.moma.org/collection/terms/de-stijl'),('MoMA — Piet Mondrian collection','https://www.moma.org/artists/4057'),('The Met — De Stijl essay','https://www.metmuseum.org/toah/hd/stij/hd_stij.htm')]},
'surrealism':{'en':'Surrealism','zh':'超现实主义','period':'c. 1924–1966','core':['unexpected scale shift','dreamlike spatial discontinuity','impossible juxtaposition','symbolic image logic'], 'secondary':['precise rendered object','quiet empty field'], 'avoid':'紫色渐变或漂浮装饰不等于超现实主义；必须让信息层级产生可控的“梦境式错位”。','refs':[('MoMA — Surrealism term','https://www.moma.org/collection/terms/surrealism'),('The Met — Surrealism essay','https://www.metmuseum.org/toah/hd/surr/hd_surr.htm'),('MoMA — René Magritte collection','https://www.moma.org/artists/3692')]},
'pop_art':{'en':'Pop Art','zh':'波普艺术','period':'c. 1950s–1970s','core':['commercial-image language','high-key contrast','repetition as rhythm','scale jump and crop'], 'secondary':['halftone field','speech-bubble framing'], 'avoid':'鲜艳颜色本身不等于波普；重复、商品化图像语言、裁切和夸张比例才是核心。','refs':[('MoMA — Pop Art term','https://www.moma.org/collection/terms/pop-art'),('MoMA — Andy Warhol collection','https://www.moma.org/artists/6246'),('The Met — Pop Art essay','https://www.metmuseum.org/toah/hd/pop/hd_pop.htm')]},
'ukiyo_e':{'en':'Ukiyo-e','zh':'浮世绘','period':'c. 1670–1900','core':['flat color planes','cropped viewpoint','directional wave or contour rhythm','asymmetric negative space'], 'secondary':['indigo-led limited palette','woodblock line and pattern'], 'avoid':'日式图标或单一海浪纹样不等于浮世绘；需采用平面色块、裁切视角、轮廓节奏与留白。','refs':[('The Met — Ukiyo-e essay','https://www.metmuseum.org/toah/hd/ukiy/hd_ukiy.htm'),('The Met — Hokusai, Great Wave','https://www.metmuseum.org/art/collection/search/45434'),('Library of Congress — Japanese woodblock prints','https://www.loc.gov/collections/japanese-fine-prints-pre-1915/about-this-collection/')]}
}

def svg(style,intensity):
    d=S[style]; n={'low':1,'medium':2,'high':3}[intensity]; label=intensity.upper(); bg='#f5f0e6'; ink='#17212b'; red='#d52b1e'; gold='#c99a36'; blue='#174d8a';
    base=f'<svg xmlns="http://www.w3.org/2000/svg" width="1440" height="900" viewBox="0 0 1440 900"><rect width="1440" height="900" fill="{bg}"/><text x="54" y="62" font-family="Arial" font-size="25" fill="{ink}">ANALYTICS / KNOWLEDGE BENCHMARK — {label}</text>'
    if style=='art_nouveau': body=f'<path d="M36 110 C210 40 270 245 410 150 S610 85 700 190 S915 280 1050 120 S1250 55 1400 150" fill="none" stroke="#1f6b5e" stroke-width="{4*n}"/><path d="M80 820 C230 650 350 820 500 700 S760 870 930 700 S1190 600 1360 790" fill="none" stroke="#bd9c4a" stroke-width="{5*n}"/><path d="M95 205 C270 150 380 310 540 230 L520 720 C370 640 240 720 95 650Z" fill="#dfe9d4" stroke="#1f6b5e" stroke-width="4"/><path d="M610 180 C850 80 1090 180 1320 245 L1300 690 C1050 620 820 735 605 650Z" fill="#fffaf0" stroke="#1f6b5e" stroke-width="4"/><circle cx="280" cy="410" r="105" fill="#bd9c4a" opacity=".7"/><path d="M680 560 C780 360 910 690 1040 450 S1260 520 1280 315" fill="none" stroke="#1f6b5e" stroke-width="{10*n}"/><g fill="#1f6b5e">'+''.join(f'<circle cx="{720+i*110}" cy="{320+(i%2)*70}" r="{12+n*4}"/>' for i in range(5))+'</g>'
    elif style=='art_deco': body=f'<path d="M720 120 L1020 400 L850 400 L850 720 L590 720 L590 400 L420 400Z" fill="#18212d"/><path d="M720 145 L950 370 L800 370 L800 750 L640 750 L640 370 L490 370Z" fill="none" stroke="{gold}" stroke-width="{5*n}"/><path d="M180 720 L180 260 L400 720 M1260 720 L1260 260 L1040 720" fill="none" stroke="{gold}" stroke-width="{8*n}"/><path d="M510 190 L720 95 L930 190 M510 770 L720 860 L930 770" fill="none" stroke="{gold}" stroke-width="{4*n}"/><g fill="{gold}">'+''.join(f'<rect x="{250+i*180}" y="{460-(i%3)*70}" width="100" height="{130+(i%3)*70}"/>' for i in range(5))+'</g>'
    elif style=='bauhaus': body=f'<rect x="80" y="155" width="370" height="590" fill="#f9f7ed" stroke="{ink}" stroke-width="{5*n}"/><circle cx="355" cy="320" r="130" fill="#dd2c22"/><rect x="510" y="155" width="265" height="210" fill="#f2c400"/><rect x="805" y="155" width="550" height="430" fill="#174d8a"/><rect x="510" y="415" width="265" height="330" fill="#17212b"/><circle cx="1040" cy="670" r="120" fill="#dd2c22"/><path d="M900 260 L1280 510 M850 710 L1310 710" stroke="#f2c400" stroke-width="{12*n}"/>'
    elif style=='constructivism': body=f'<path d="M20 730 L620 130 L810 310 L330 790Z" fill="#d52b1e"/><path d="M450 790 L1000 150 L1420 250 L930 790Z" fill="#17212b"/><path d="M220 265 L1360 520" stroke="#d52b1e" stroke-width="{20*n}"/><path d="M90 625 L1160 205" stroke="{bg}" stroke-width="{12*n}"/><g fill="{bg}">'+''.join(f'<rect x="{760+i*85}" y="{400-i*32}" width="65" height="{120+i*20}" transform="rotate(-22 {760+i*85} {400-i*32})"/>' for i in range(5))+'</g>'
    elif style=='de_stijl': body=f'<rect x="80" y="130" width="1280" height="650" fill="white" stroke="black" stroke-width="{8*n}"/><path d="M350 130V780M770 130V780M1090 130V780M80 360H1360M80 600H1360" stroke="black" stroke-width="{8*n}"/><rect x="88" y="138" width="254" height="214" fill="#d82029"/><rect x="778" y="608" width="304" height="164" fill="#f3c315"/><rect x="1098" y="368" width="254" height="224" fill="#144a9a"/>'
    elif style=='surrealism': body=f'<rect x="65" y="150" width="500" height="570" fill="#e3edf0" stroke="{ink}" stroke-width="4"/><rect x="680" y="270" width="600" height="370" fill="#f2d9b6" stroke="{ink}" stroke-width="4"/><ellipse cx="315" cy="460" rx="185" ry="95" fill="#244b8f"/><rect x="800" y="150" width="220" height="420" rx="110" fill="#d65b32"/><circle cx="1130" cy="300" r="120" fill="#e9d44c"/><path d="M280 170 C420 260 300 330 420 420 S350 650 500 720" fill="none" stroke="#17212b" stroke-width="{7*n}"/><path d="M570 700 C760 580 900 790 1120 610 S1320 690 1370 470" fill="none" stroke="#17212b" stroke-width="{7*n}"/>'
    elif style=='pop_art': body=f'<rect x="70" y="135" width="400" height="600" fill="#ffe145" stroke="{ink}" stroke-width="{7*n}"/><rect x="495" y="135" width="390" height="600" fill="#f02d59" stroke="{ink}" stroke-width="{7*n}"/><rect x="910" y="135" width="460" height="600" fill="#23a9db" stroke="{ink}" stroke-width="{7*n}"/><g fill="#17212b">'+''.join(f'<circle cx="{125+(i%5)*70}" cy="{210+(i//5)*70}" r="8"/>' for i in range(35))+'</g><path d="M565 240 L805 210 L770 430 L840 500 L610 560 L640 395Z" fill="white" stroke="{ink}" stroke-width="{8*n}"/><path d="M980 600 L1290 250 L1340 660Z" fill="#ffe145" stroke="{ink}" stroke-width="{8*n}"/>'
    else: body=f'<path d="M45 735 C220 510 355 715 525 600 S825 350 1040 560 S1270 680 1390 420" fill="none" stroke="#164d8d" stroke-width="{14*n}"/><path d="M80 210 L540 155 L470 420 L120 475Z" fill="#e7c35c" stroke="#163456" stroke-width="4"/><path d="M600 135 L1260 220 L1140 485 L670 390Z" fill="#f3eee3" stroke="#163456" stroke-width="4"/><path d="M170 600 L540 520 L730 770 L280 770Z" fill="#2f7c8b"/><path d="M830 520 L1310 450 L1280 760 L870 730Z" fill="#d6624b"/><g stroke="#163456" stroke-width="{4*n}" fill="none">'+''.join(f'<path d="M{100+i*125} 820 q55 -120 110 0"/>' for i in range(10))+'</g>'
    return base+body+f'<text x="55" y="860" font-family="Arial" font-size="34" font-weight="700" fill="{ink}">{d["en"]} — DNA-led UI translation draft</text></svg>'

def md(style):
 d=S[style]; refs='\n'.join(f'- {name}: {url}' for name,url in d['refs']); core='\n'.join(f'- `{x}` — CORE' for x in d['core']); sec='\n'.join(f'- `{x}` — SECONDARY' for x in d['secondary'])
 return f'''# {d['en']} / {d['zh']} — Style DNA
\n## Historical Definition
{d['period']}；本目录只将其作为有明确艺术史与设计史语境的 `ART_HISTORY_STYLE` 管理。\n\n## Core References\n{refs}\n\n## Core DNA\n{core}\n\n## Secondary DNA\n{sec}\n\n## Composition\n将视觉重心、轴线、留白和边缘处理视作风格的第一载体；不以名称或色板替代构图。\n\n## Shape / Line / Rhythm\n形状、线条连续性、重复节奏必须共同对应核心规则；预览中应能从版式而非标题辨认。\n\n## Color / Typography / Surface / Ornament\n颜色承担层级或区隔功能；字体、纹理与装饰只在不损害可读性时服务结构。\n\n## Common Misinterpretations\n{d['avoid']}\n\n## Evidence policy\n每个 CORE 规则应在上述至少一个历史参考中得到复核；网络参考仅用于本地研究，必须保留 URL、采集时间和许可状态。\n'''
def trans(style):
 d=S[style]
 return f'''# {d['en']} — UI Translation
\n## Structure\n以 `{d['core'][0]}` 和 `{d['core'][1]}` 改造布局、网格、对齐和层级；禁止在固定 SaaS 卡片模板上仅改变皮肤。\n\n## Components\n面板、卡片、分割线、导航和图表应复用同一形状与节奏规则；关键数据仍须可扫描、可对比。\n\n## Typography / Color\n文字层级和色彩关系必须支持信息结构。历史色彩逻辑被转换为数字界面中的强调、状态和分区，而不是复刻旧作配色。\n\n## Ornament / Image / Motion\n装饰只锚定边框、分区、插图或导航节点；图像与动效必须强化 `{d['core'][2]}`，不可遮蔽数据。\n\n## Intensity\n- **LOW**：保持成熟产品框架，仅引入少量 CORE DNA。\n- **MEDIUM**：布局、形状、字级和色彩关系明显受影响。\n- **HIGH**：允许强构图与强图形语言，但保留导航、筛选、KPI、图表、列表、表格和状态。\n\n## Do\n- 使用 Style DNA 作为生成和评审依据。\n- 对同一 Benchmark 内容实施结构变化。\n\n## Avoid\n- 只换色、纹理或装饰；此类结果标记为 `SURFACE_MIMICRY`。\n- 使用历史作品中的人物或题材取代形式语言。\n'''
def main():
 OUT.mkdir(parents=True,exist_ok=True)
 registry=[]
 for key,d in S.items():
  p=OUT/key; (p/'references'/'historical').mkdir(parents=True,exist_ok=True); (p/'references'/'ui_translation').mkdir(parents=True,exist_ok=True); (p/'previews').mkdir(exist_ok=True)
  hist=[{'id':f'{key}_h{i+1}','title':n,'source_url':u,'source_type':'MUSEUM_OR_INSTITUTION_PAGE','captured_at':NOW,'license_status':'REFERENCE_PAGE_ONLY—image license must be checked before download','usage_scope':'Local design research and visual analysis only; never publish as owned commercial asset.'} for i,(n,u) in enumerate(d['refs'])]
  (p/'references'/'historical'/'reference_manifest.json').write_text(json.dumps(hist,ensure_ascii=False,indent=2),encoding='utf-8')
  obj={'id':key,'name_en':d['en'],'name_zh':d['zh'],'taxonomy':'ART_HISTORY_STYLE','historical_period':d['period'],'style_dna':{'core':d['core'],'secondary':d['secondary']},'ui_translation_status':'DRAFT_STRUCTURED','preview_status':'VECTOR_TRANSLATION_DRAFT—BLIND_TEST_REQUIRED','placeholder_preview':False,'references':hist,'previews':[f'previews/{x}.svg' for x in ('low','medium','high')]}
  (p/'style.json').write_text(json.dumps(obj,ensure_ascii=False,indent=2),encoding='utf-8'); (p/'STYLE_DNA.md').write_text(md(key),encoding='utf-8'); (p/'UI_TRANSLATION.md').write_text(trans(key),encoding='utf-8')
  for intensity in ('low','medium','high'): (p/'previews'/f'{intensity}.svg').write_text(svg(key,intensity),encoding='utf-8')
  registry.append(obj)
 (OUT/'ART_HISTORY_STYLE_FIRST_WAVE.json').write_text(json.dumps(registry,ensure_ascii=False,indent=2),encoding='utf-8')
 # Reclassify the legacy art list without pretending that it has passed the new DNA workflow.
 legacy_path=ROOT/'data'/'art_styles.json'
 legacy=json.loads(legacy_path.read_text(encoding='utf-8'))
 core=set(S); digital={'cyberpunk','vaporwave','synthwave','y2k','retro_futurism','pixel_art','low_poly','isometric','3d_clay','3d_illustration','holographic','glitch_art','generative_art','aurora'}
 technique={'flat_illustration','vector_illustration','line_art','hand_drawn','sketch','ink_illustration','woodcut','screen_print','risograph','paper_cut','collage','editorial_illustration','engraving','etching','ornamental_line','botanical'}
 theme={'dunhuang','song_painting','korean_editorial','minhwa','beardsley','victorian','gothic','dark_romanticism','topographic'}
 taxonomy=[]
 for x in legacy:
  slug=x['id'].removeprefix('art_')
  kind='ART_HISTORY_STYLE' if slug in core else ('DIGITAL_AESTHETIC' if slug in digital else ('VISUAL_TECHNIQUE' if slug in technique else ('THEME' if slug in theme else 'ATTRIBUTE')))
  taxonomy.append({'id':x['id'],'name_en':x['name_en'],'taxonomy':kind,'rebuild_status':'FIRST_WAVE_COMPLETE' if slug in core else 'RECLASSIFIED—DNA_REBUILD_PENDING','legacy_preview_status':'PLACEHOLDER_PREVIEW'})
 (ROOT/'data'/'art_style_taxonomy.json').write_text(json.dumps(taxonomy,ensure_ascii=False,indent=2),encoding='utf-8')
 sources_path=ROOT/'sources'/'image_sources.json'; sources=json.loads(sources_path.read_text(encoding='utf-8'))
 for rel,item in sources.items():
  if rel.startswith('images/art/'):
   item['asset_status']='PLACEHOLDER_PREVIEW'; item['retrieval_eligible']=False; item['fidelity_validation_eligible']=False; item['training_reference_eligible']=False
 sources_path.write_text(json.dumps(sources,ensure_ascii=False,indent=2),encoding='utf-8')
 report='''# Visual Style Rebuild Status\n\n## Completed structural rebuild\n\n- First wave: 8 ART_HISTORY_STYLE records.\n- Each record: 3 museum/institution reference pages, Style DNA, UI translation rules, and LOW/MEDIUM/HIGH benchmark preview drafts.\n- Existing `images/art/**/preview_01.svg` remains `PLACEHOLDER_PREVIEW`; it must not enter retrieval, fidelity validation, or training reference sets.\n\n## Pending before STYLE_TRANSLATION_COMPLETE\n\n- Download/verify individual historical reference images and their licenses if visual files are needed.\n- Produce high-fidelity previews from DNA (AI generation attempt failed because image service network was unavailable).\n- Run blinded human/model discrimination and score Style Fidelity >=75.\n- Confirm usability for each intensity.\n'''
 (ROOT/'reports'/'VISUAL_STYLE_REBUILD_STATUS.md').write_text(report,encoding='utf-8')
if __name__=='__main__': main()
