/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalysisPanel: typeof import('./src/components/opinion/AnalysisPanel.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    CaseLibraryPanel: typeof import('./src/components/opinion/CaseLibraryPanel.vue')['default']
    DataCard: typeof import('./src/components/DataCard.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EntityDetail: typeof import('./src/components/opinion/EntityDetail.vue')['default']
    EntityFilterPanel: typeof import('./src/components/opinion/EntityFilterPanel.vue')['default']
    GraphToolbar: typeof import('./src/components/opinion/GraphToolbar.vue')['default']
    GraphVisualization: typeof import('./src/components/GraphVisualization.vue')['default']
    InsightPanel: typeof import('./src/components/opinion/InsightPanel.vue')['default']
    LoginGate: typeof import('./src/components/LoginGate.vue')['default']
    OpinionLegend: typeof import('./src/components/opinion/OpinionLegend.vue')['default']
    RelationDetail: typeof import('./src/components/opinion/RelationDetail.vue')['default']
    RiskGaugeChart: typeof import('./src/components/charts/RiskGaugeChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SentimentTrendChart: typeof import('./src/components/charts/SentimentTrendChart.vue')['default']
    StatusBadge: typeof import('./src/components/StatusBadge.vue')['default']
    TopicDistributionChart: typeof import('./src/components/charts/TopicDistributionChart.vue')['default']
  }
}
